import PDFDocument from 'pdfkit';
import fs from 'fs';

class PdfService {
  getImageSource(image) {
    if (!image || !String(image).startsWith('data:image/')) return image;
    const match = String(image).match(/^data:image\/[^;]+;base64,(.+)$/);
    return match ? Buffer.from(match[1], 'base64') : image;
  }
  /**
   * Generates a PDF receipt and returns it as a Buffer
   * @param {Object} data Receipt data
   * @returns {Promise<Buffer>}
   */
  async generateReceiptPdf(data) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: [226, 900],
          margins: { top: 24, bottom: 24, left: 18, right: 18 },
        });
        const buffers = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
          const pdfData = Buffer.concat(buffers);
          resolve(pdfData);
        });
        doc.on('error', reject);

        this._buildReceiptContent(doc, data);

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  async generateReportPdf(data) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ size: 'A4', margin: 42 });
        const buffers = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        const rawLogoPath = data.logo || process.env.BUSINESS_LOGO_PATH;
        const logoExists = rawLogoPath && (String(rawLogoPath).startsWith('data:image/') || fs.existsSync(rawLogoPath));
        const logoPath = this.getImageSource(rawLogoPath);
        if (logoExists) {
          doc.opacity(0.06).image(logoPath, 220, 300, { fit: [150, 150] }).opacity(1);
          doc.image(logoPath, 274, 35, { fit: [48, 48] });
        }
        const reportHeaderY = logoExists ? 92 : 45;
        doc.fillColor('#102b50').font('Helvetica-Bold').fontSize(18)
          .text(data.businessName || process.env.BUSINESS_NAME || 'RMS House Rental & Management', 42, reportHeaderY, { width: 511, align: 'center' })
          .fontSize(12).text('Financial & Occupancy Report', 42, reportHeaderY + 25, { width: 511, align: 'center' })
          .font('Helvetica').fontSize(9).fillColor('#475569')
          .text(`Generated: ${new Date().toLocaleString()}`, 42, reportHeaderY + 44, { width: 511, align: 'center' });
        const reportContentY = reportHeaderY + 68;
        doc.strokeColor('#cbd5e1').moveTo(42, reportContentY).lineTo(553, reportContentY).stroke();

        let y = reportContentY + 28;
        doc.fillColor('#102b50').font('Helvetica-Bold').fontSize(12).text('Summary', 42, y);
        y += 24;
        doc.font('Helvetica').fontSize(10).fillColor('#334155')
          .text(`Total revenue: KES ${Number(data.kpis?.totalRevenue || 0).toLocaleString()}`, 42, y)
          .text(`Total bookings: ${data.kpis?.totalBookings || 0}`, 300, y)
          .text(`Occupancy: ${data.kpis?.occupancyRate || 0}%`, 42, y + 18)
          .text(`Available properties: ${data.kpis?.totalProperties || 0}`, 300, y + 18);
        y += 60;
        doc.font('Helvetica-Bold').fillColor('#102b50').text('Top Properties', 42, y);
        y += 24;
        (data.topProperties || []).forEach((property) => {
          doc.font('Helvetica').fontSize(9).fillColor('#334155')
            .text(property.name || 'Property', 48, y, { width: 300 })
            .text(`KES ${Number(property.revenue || 0).toLocaleString()}`, 400, y, { width: 110, align: 'right' });
          y += 18;
        });
        y += 16;
        doc.font('Helvetica-Bold').fillColor('#102b50').text('Payment Methods', 42, y);
        y += 24;
        (data.paymentBreakdown || []).forEach((payment) => {
          doc.font('Helvetica').fontSize(9).fillColor('#334155')
            .text(String(payment.method || '').toUpperCase(), 48, y)
            .text(`KES ${Number(payment.total || 0).toLocaleString()} (${payment.count || 0} transactions)`, 260, y, { width: 250, align: 'right' });
          y += 18;
        });
        doc.fontSize(9).fillColor('#64748b').text('Generated by RMS Rental Management System', 42, 760, { align: 'center', width: 511 });
        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  _buildReceiptContent(doc, data) {
    const width = 190;
    const money = (value) => `${data.billing.currency || 'KES'} ${Number(value || 0).toLocaleString('en-KE', { minimumFractionDigits: 2 })}`;
    const rawLogoPath = data.business?.logo || process.env.BUSINESS_LOGO_PATH;
    const logoExists = rawLogoPath && (String(rawLogoPath).startsWith('data:image/') || fs.existsSync(rawLogoPath));
    const logoPath = this.getImageSource(rawLogoPath);

    if (logoExists) {
      doc.image(logoPath, 73, 22, { fit: [80, 42], align: 'center' });
      doc.opacity(0.06).image(logoPath, 50, 310, { fit: [125, 125], align: 'center' }).opacity(1);
    }

    doc.fillColor('#102b50').font('Helvetica-Bold').fontSize(13)
      .text(data.business?.name || 'RMS House Rental & Management', 18, logoExists ? 70 : 28, { width, align: 'center' })
      .font('Helvetica').fontSize(8).fillColor('#475569')
      .text(data.business?.phone || '+254 700 000000', { width, align: 'center' })
      .text(data.business?.email || 'support@rms-rentals.com', { width, align: 'center' });

    doc.moveDown(0.7).strokeColor('#cbd5e1').lineWidth(0.7).moveTo(18, doc.y).lineTo(208, doc.y).stroke();
    doc.moveDown(0.7).fillColor('#102b50').font('Helvetica-Bold').fontSize(11)
      .text('PAYMENT RECEIPT', { width, align: 'center' })
      .font('Helvetica').fontSize(8).fillColor('#475569')
      .text(`Receipt: ${data.receiptNumber}`, { width, align: 'center' })
      .text(`Issued: ${new Date(data.issuedAt || Date.now()).toLocaleString()}`, { width, align: 'center' });

    doc.moveDown(0.8).font('Helvetica-Bold').fillColor('#102b50').fontSize(9).text('GUEST');
    doc.font('Helvetica').fillColor('#334155').fontSize(8)
      .text(data.customer?.name || 'Valued Customer')
      .text(data.customer?.phone || data.customer?.email || '');
    doc.moveDown(0.5).font('Helvetica-Bold').fillColor('#102b50').text('STAY');
    doc.font('Helvetica').fillColor('#334155')
      .text(data.property?.name || 'Rental Unit', { width })
      .text(`${data.stay?.checkInDate || ''} to ${data.stay?.checkOutDate || ''}`)
      .text(`${data.billing?.paymentMethod || ''} | ${data.billing?.transactionRef || ''}`);

    doc.moveDown(0.8).strokeColor('#cbd5e1').moveTo(18, doc.y).lineTo(208, doc.y).stroke();
    doc.moveDown(0.6).font('Helvetica').fillColor('#334155').fontSize(8)
      .text(`Subtotal${' '.repeat(1)}${money(data.billing.subtotal)}`, { width, align: 'right' })
      .text(`VAT ${data.billing.taxRate}${' '.repeat(1)}${money(data.billing.taxAmount)}`, { width, align: 'right' })
      .font('Helvetica-Bold').fontSize(11).fillColor('#102b50')
      .text(`TOTAL PAID  ${money(data.billing.amountPaid)}`, { width, align: 'right' });

    doc.moveDown(1).font('Helvetica').fontSize(8).fillColor('#64748b')
      .text(`Balance remaining: ${money(data.billing.balanceRemaining)}`, { width, align: 'center' })
      .text(`PIN: ${data.business?.pinNumber || 'P051234567Z'}`, { width, align: 'center' })
      .text('Thank you for your business.', { width, align: 'center' });
  }
}

export default new PdfService();
